name = "MultiShapeCellLists"
uuid = "fbe69cd6-f244-4ce4-a90b-8979d86c9ea4"
authors = ["Nathan Zimmerberg"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
